[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PosEng"
authors = [{name = "Gavin Dalton", email = "gavindalton8@gmail.com"}]
dynamic = ["version", "description"]
